### ISSUE TITLE
Thank you, Question

### ISSUE THREAD

**Issue by thebradleysanders** [korylprince/hassio-apcupsd#15] opened 2019-09-20 19:37 UTC
I have a couple APCs that communicate over USB, does this add-on support multiple units? If so how can I do this?

**Comment by korylprince** [comment] 2019-09-21 21:20
This is a duplicate of Issue #3. TL;DR: No, it doesn't, and it's not a planned feature at this point.

**Closed as completed by korylprince** 2019-09-21 21:20 UTC
Labels: duplicate
