### ISSUE TITLE
Proxmox LXC

### ISSUE THREAD

**Issue by tamet83** [korylprince/hassio-apcupsd#16] opened 2019-12-21 13:34 UTC
Hi,

I've setup a new instance of Hassio with [Whiskerz scritp](https://github.com/whiskerz007/proxmox_hassio_lxc).

I have both a ConBee stick and and APC UPS USB.

When i try to run the addon I receive this error:

`ERROR (SyncWorker_1) [hassio.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/usb/": no such file or directory")`

Do you have any advice how to solve this problem?

This hare the devices listed in my Hass.io instance:
```
serial:
/dev/ttyS0
/dev/ttyS16
/dev/ttyS8
/dev/ttyS2
/dev/ttyS7
/dev/ttyS14
/dev/ttyS5
/dev/ttyS20
/dev/ttyS18
/dev/ttyS15
/dev/ttyS19
/dev/ttyS26
/dev/ttyS28
/dev/ttyS3
/dev/ttyS25
/dev/ttyS11
/dev/ttyS29
/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO01MI89-if00-port0
/dev/ttyS22
/dev/ttyS6
/dev/ttyS31
/dev/ttyUSB0
/dev/ttyS4
/dev/ttyS17
/dev/ttyS27
/dev/ttyS23
/dev/ttyS9
/dev/ttyS12
/dev/ttyS1
/dev/ttyS21
/dev/ttyS30
/dev/ttyS10
/dev/ttyS13
/dev/ttyS24
input:
HDA Intel PCH HDMI/DP,pcm=8
HDA Intel PCH Mic
Sleep Button
PC Speaker
HDA Intel PCH Front Headphone
Power Button
HDA Intel PCH HDMI/DP,pcm=7
HDA Intel PCH HDMI/DP,pcm=3
HDA Intel PCH HDMI/DP,pcm=10
HDA Intel PCH HDMI/DP,pcm=9
Video Bus
disk:
gpio:
gpiochip200
gpiochip196
audio:
0:
name: HDA-Intel - HDA Intel PCH
type: PCH
devices:
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
```
``

**Comment by korylprince** [comment] 2019-12-21 19:50
You'll need to use udev rules to make your APC UPS USB device show up as `/dev/usb/hiddevX` so that Hass.io can see it. I don't know the details of doing that on Proxmox/LXC, but I'd start with making the `/dev/usb/hiddevX` device show up on your physical host, then work on getting it passed into the LXC container.

There's some udev rule info on [this page](https://wiki.debian.org/apcupsd) that may be helpful.

**Comment by tamet83** [comment] 2019-12-22 22:22
Because of my lack of knowledge whit Linux in general, I think I won’t be able to do it alone.
I wrote to whiskerz007 and see if he can make some changes to his script.
Anyway, thanks for your help, really appreciate it.

**Comment by gomez85** [comment] 2020-01-08 19:27
Hi @korylprince , I've the same tamet83 problem and I'd tried to use udev rules as your suggestion but when I try to start the addon i retrieve this error:

`[hassio.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/usb/": not a device node")`

If helping, my device is located in /dev/bus/usb/003/002

Can you help me?

**Comment by korylprince** [comment] 2020-01-10 00:14
The problem is the same: you've got to get the `/dev/usb/*` devices to show up to hass.io so that it can put them into the apcupsd container. I'm not very familiar with LXC, and you're much more likely to get a solution from the [issue](https://github.com/whiskerz007/proxmox_hassio_lxc/issues/11) on the proxmox_hassio_lxc project.

**Comment by Giancky79** [comment] 2020-01-10 06:47
maybe the problem is debian10 and apcupsd?

**Comment by gomez85** [comment] 2020-01-10 12:05
@korylprince thanks for the reply.. isn't possible by the addon configuration set manually the path? Because the problem isn't LXC but maybe how debian10 manage the usb devices

**Comment by korylprince** [comment] 2020-01-12 03:15
This add-on is limited by [this issue](https://github.com/home-assistant/hassio-supervisor/issues/331), unfortunately; I can only hard-set device paths for the add-on.

I'm going to go ahead and close this issue, as it's not fixable by this project. If you're not going to use the standard Hass.io installations (which puts the devices in the proper places), it will be up to you to use udev rules or some other mechanism to populate the `/dev/usb/*` devices.

**Closed as completed by korylprince** 2020-01-12 03:15 UTC

**Comment by gomez85** [comment] 2020-01-12 15:14
@korylprince , I answer even if you have closed the issue, to tell you that the problem was in the management of resources in my system with Proxmox, LXC and VM. So I confirm that with the latest revision of the [whiskerz script](https://github.com/whiskerz007/proxmox_hassio_lxc) everything works as you can see in the my [comment](https://github.com/whiskerz007/proxmox_hassio_lxc/issues/11#issuecomment-573421923) in his script issue.

Thank you

**Comment by korylprince** [comment] 2020-01-12 19:07
Awesome! Glad you were able to get it working. Thanks for posting back here with a solution.
